# Site settings
title: Jekyll-Tips
email: andrewlandry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tips and tricks for users of Jekyll, the world's most popular static site generator.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jekyll-notes.com" # the base hostname & protocol for your site
twitter_username: Bits_and_Beeps
github_username:  andyroo2000

# Build settings
markdown: kramdown
